name: Fairness Audit CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"  # Weekly on Sunday

jobs:
  fairness_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run fairness audit script
        run: python scripts/run_fairness_audit.py data/biased_sample_dataset.csv
